name: Build and Analyze

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      # Setup Node.js for Angular app
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install specific version of SonarQube scanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner --version 5.13.1

      - name: Update ReportGenerator to a specific version
        run: dotnet tool update dotnet-reportgenerator-globaltool -g --version 5.1.25

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Sonar Scanner CLI
        run: choco install sonarqube-scanner.portable

      - name: Build .NET Project (Web API)
        run: dotnet build ./webapi/webapi.csproj

      # Build Angular App
      - name: Build Angular App
        run: |
          cd angular
          npm install -g @angular/cli
          npm install
          ng build
          
      - name: Build .NET Unit Tests (Opcjonalnie)
        run: dotnet build ./webapiUnitTests/webapiUnitTests.csproj
        
      - name: Run Sonar Analysis and Unit Tests for .NET
        run: |
          dotnet sonarscanner begin /k:"Sendej7_CharSheetForge_AYqKyYSB222sTEAu7r1E" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.coverageReportPaths=".\sonarqubecoverage\SonarQube.xml"
          dotnet build
          dotnet test --no-build --collect:"XPlat Code Coverage"
          reportgenerator "-reports:*\TestResults\*\coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
