name: Build and Analyze

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Setup Node.js for React app
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Install SonarQube scanner for .NET
      - name: Install SonarQube scanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      # Add dotnet tools to PATH
      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Install General Sonar Scanner CLI
      - name: Install Sonar Scanner CLI
        run: choco install sonarqube-scanner.portable

      # Build .NET Project
      - name: Build .NET Project
        run: |
          cd webapi
          dotnet build

      # Build React App
      - name: Build React App
        run: |
          cd reactapp
          npm install
          npm run build

      # Run Sonar Analysis
      - name: Run Sonar Analysis
        run: |
          cd reactapp
          sonar-scanner -D"sonar.projectKey=Sendej7_CharSheetForge_AYqKyYSB222sTEAu7r1E" -D"sonar.sources=src" -D"sonar.host.url=${{ secrets.SONAR_HOST_URL }}" -D"sonar.login=${{ secrets.SONAR_TOKEN }}"
                    sonar-scanner begin /k:"Sendej7_CharSheetForge_AYqKyYSB222sTEAu7r1E" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          cd ../webapi
          dotnet sonarscanner begin /k:"Sendej7_CharSheetForge_AYqKyYSB222sTEAu7r1E" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
